version: "3.6"

services: 
  postgres:
    image: "postgres:latest"
    container_name: "motus-test-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
    volumes:
      - ./database:/var/lib/postgresql/data
  authservice:
    build: ./
    container_name: "auth-api"
    working_dir: /app
    links: 
      - postgres
    ports: 
      - "9000:9000"
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_PORT=5432
      - MOTUS_JWT_SECRET=$MOTUS_JWT_SECRET
    
  
      